#!/usr/bin/env python

import lastone
import lastone.ai

board = lastone.Board()

player1 = lastone.ai.QPlayer(board)
player2 = lastone.ai.QPlayer(board)

game = lastone.Game(player1, player2)

game.run(board)